server:
  port: 8082

spring:
  application:
    name: ms-barriodigital-requests

  datasource:
    url: jdbc:mysql://localhost:3307/db_barriodigital?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: barriouser
    password: barriopassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer